import parmed as pmd

# Load the prmtop and inpcrd files using ParmEd
system = pmd.load_file('../../1-sys_prep/box.prmtop', '../../1-sys_prep/box.inpcrd')


# Define an AmberMask that selects all ions
rna_mask = ':G5,C3,G,C,U,A | @1090-1121'

rna_selection = pmd.amber.AmberMask(system, rna_mask)
system.strip(rna_selection)


# Save the modified prmtop file
system.save('newfile.prmtop', overwrite=True)

# Create a new inpcrd file with only the selected atoms
with open('newfile.inpcrd', 'w') as f:
    f.write(f'{system.coordinates.shape[0]}\n')
    f.write(f'Generated by ParmEd from input_file\n')
    for coords in system.coordinates:
        f.write(f'{coords[0]:.7f} {coords[1]:.7f} {coords[2]:.7f}\n')

# Save a PDB file of the stripped system
system.write_pdb('newfile.pdb')
