#!/bin/bash

#####################################################################
## This script adds a line to conf files generated by BFEE
## to support 4-point water model for OPC simulations.
#####################################################################



## make sure ambertools environment is properly setup before running this script
## you can activate the ambertools even before running this script to make sure you 
## have the right env
# conda activate ambertools

## set the list of compounds (dir_list), conditions (cond_list),
## and replicas (rep_list) that need to be fixed
# dir_list="2-theophylline 3-1_methylxanthine 4-3_methylxanthine 5-hypoxanthine 6-xanthine 7-caffeine"
dir_list="5-hypoxanthine"
cond_list="3-55NaCl_Mg"
# rep_list="1-rep1 2-rep2 3-rep3"
rep_list=" 3-rep3_2"
WD=$PWD
## set common directory path
cmn_dir="/home/arasouli/repos/alchemical/rna_small_molecule_FE/common_files"

## loop over the compounds, conditions and replicas
## and add the line to the conf files
for val1 in $dir_list; do
    cd ${val1}
    for val2 in $cond_list; do
        cd ${val2}/6-opc_40winCmplx_30winLig/
        for val3 in $rep_list; do
            cd ${val3}/2-sim_run/BFEE
            sed -i '3iwatermodel tip4' */*.conf
            cp ${cmn_dir}/run_1_BFEE_opc.sh .
            cd ../../../
        done
        cd ../../
    done
    cd ..
done


