import parmed as pmd

# Load the prmtop and inpcrd files using ParmEd
system = pmd.load_file('../../1-sys_prep/box.prmtop', '../../1-sys_prep/box.inpcrd')

# Define an AmberMask that selects RNA and all ions to be removed
# Warning! The sodium atoms to remove are hard coded. 
# For new systems make sure to select atom indices of sodiums you want to remove, 
# so that final system is neutral.
# Here, atom index of 31 sodiums masked to make neutral system: 1090-1121
rna_mask = ':G5,C3,G,C,U,A | @1090-1121'

rna_selection = pmd.amber.AmberMask(system, rna_mask)
system.strip(rna_selection)


# Save the modified prmtop file
system.save('ligandOnly.parm7', overwrite=True)

# Create a new inpcrd file with only the selected atoms
with open('ligandOnly.inpcrd', 'w') as f:
    f.write(f'{system.coordinates.shape[0]}\n')
    f.write(f'Generated by ParmEd from input_file\n')
    for coords in system.coordinates:
        f.write(f'{coords[0]:.7f} {coords[1]:.7f} {coords[2]:.7f}\n')

# Save a PDB file of the stripped system
system.write_pdb('ligandOnly.pdb')